apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 953865769063.dkr.ecr.ap-southeast-1.amazonaws.com/demo-frontend
  newName: 953865769063.dkr.ecr.ap-southeast-1.amazonaws.com/demo-frontend
  newTag: 07d34a72
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
